### PR TITLE
Added CONTRIBUTING.md and CODE_OF_CONDUCT.md

### LINKED ISSUE #4: Add CONTRIBUTING.md and CODE_OF_CONDUCT.md
In the spirit of getting more contributors to the project, the above documents would be appreciated.

### PR DESCRIPTION
**Pull request by bislara**
I solved the #4  issue. ie ( Add CONTRIBUTING.md and CODE_OF_CONDUCT.md )
Please check and let me know if you need any changes.

### CODE REVIEW

**Comment by bislara** [comment]
@t0xic0der  Hey can you please review this PR and merge it?

**Review by gridhead — COMMENTED** [review]
There has been a change in the policies of Hacktoberfest participation that you would want to take a look at. https://hacktoberfest.digitalocean.com/hacktoberfest-update.

**Review by gridhead — CHANGES_REQUESTED** [review]
Could you run the CONTRIBUTING.md once through a Grammarly check? There are some typographical mistakes that require attention.

**Comment by bislara** [comment]
> There has been a change in the policies of Hacktoberfest participation that you would want to take a look at. https://hacktoberfest.digitalocean.com/hacktoberfest-update.

Thank you so much for sharing this. I am also one of the maintainers. I will the guidelines

**Comment by bislara** [comment]
> Could you run the CONTRIBUTING.md once through a Grammarly check? There are some typographical mistakes that require attention.

Sure I will check once and fix the mistakes

**Comment by bislara** [comment]
Done. Kindly check once again. If there is still something wrong, feel free to mention

**Review by gridhead — APPROVED** [review]
LGTM. Merging.

**Pull request merged**
